pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Клонировать репозиторий содержащий Helm чарт
                git 'https://github.com/devaliops/testovoeSBER/tree/main'
            }
        }

        stage('Install Helm and Minikube') {
            steps {
                // Установить Helm и Minikube, если они еще не установлены
                sh 'curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3'
                sh 'chmod 700 get_helm.sh && ./get_helm.sh'
                sh 'curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/'
                sh 'minikube start'
            }
        }

        stage('Install Nginx Helm Chart') {
            steps {
                // Установить Helm чарт Nginx
                sh 'helm install nginx-release ./nginx-chart'
            }
        }

        stage('Verify Installation') {
            steps {
                // Проверить, что установка прошла успешно
                sh 'kubectl get pods'
            }
        }
    }
}
