# values.yaml

image:
  repository: nginx
  tag: latest

service:
  type: NodePort
  port: 80
  nodePort: 32080

labels:
  app: nginx
  tier: frontend

nginx:
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent